export type Theme = "floral" | "marble" | "animal" | "food" | "botanical" | "geometric" | "abstract" | "vintage" | "celestial" | "coastal" | "japanese" | "outdoor";

export type Status = "pending" | "generated" | "approved" | "submitted";

export type Source = "burga" | "casetify" | "skinnydip" | "society6" | "original";

export const SOURCE_LABELS: Record<Source, string> = {
  burga:     "BURGA",
  casetify:  "CASETiFY",
  skinnydip: "Skinnydip",
  society6:  "Society6",
  original:  "Original",
};

export interface Design {
  id: string;
  theme: Theme;
  source: Source;
  sourceRef: string;
  sourceUrl: string;
  name: string;
  prompt: string;
}

export const THEMES = [
  { id: "all", label: "ALL", jp: "全て" },
  { id: "floral", label: "FLORAL", jp: "フローラル" },
  { id: "marble", label: "MARBLE", jp: "マーブル" },
  { id: "animal", label: "ANIMAL", jp: "アニマル" },
  { id: "food", label: "FOOD", jp: "フード" },
  { id: "botanical", label: "BOTANICAL", jp: "ボタニカル" },
  { id: "geometric", label: "GEOMETRIC", jp: "幾何学" },
  { id: "abstract", label: "ABSTRACT", jp: "アブストラクト" },
  { id: "vintage", label: "VINTAGE", jp: "ヴィンテージ" },
  { id: "celestial", label: "CELESTIAL", jp: "天体" },
  { id: "coastal", label: "COASTAL", jp: "コースタル" },
  { id: "japanese", label: "JAPANESE", jp: "和風" },
  { id: "outdoor", label: "OUTDOOR", jp: "アウトドア" },
] as const;

export const STATUSES = [
  { id: "pending",   jp: "未着手", bg: "#F0EAE0", fg: "#8B7355", border: "#D4C5A9" },
  { id: "generated", jp: "生成済", bg: "#E0EAF0", fg: "#3A6B8C", border: "#AACBD9" },
  { id: "approved",  jp: "OK",    bg: "#DEE8D7", fg: "#4A6B3A", border: "#AAC799" },
  { id: "submitted", jp: "入稿",  bg: "#EADCE7", fg: "#6B3A5C", border: "#C9A3C0" },
] as const;

export const DESIGNS: Design[] = [
  // 1. FLORAL (001-010)
  { id: "001", theme: "floral", source: "burga", sourceRef: "Sakura", sourceUrl: "https://burga.com/products/sakura-airpods-pro-3-case", name: "Sakura Pink", prompt: "Seamless pattern of soft pink cherry blossoms with delicate branches, Japanese watercolor style, on cream background, feminine and serene, tileable, no text" },
  { id: "002", theme: "floral", source: "burga", sourceRef: "Lush Meadows", sourceUrl: "https://burga.com/products/floral-airpods-pro-case", name: "Lush Meadow", prompt: "Seamless pattern of mixed wildflowers including daisies poppies and cornflowers, loose painterly style, vibrant colors on sage green background, romantic, tileable, no text" },
  { id: "003", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Vintage Rose", prompt: "Seamless pattern of deep red roses with dark green leaves, vintage oil painting style, on burgundy background, moody and romantic, tileable, no text" },
  { id: "004", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Pastel Peony", prompt: "Seamless pattern of large blush pink peonies in full bloom, soft watercolor wash, on ivory background, dreamy and feminine, tileable, no text" },
  { id: "005", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Tropical Hibiscus", prompt: "Seamless pattern of bold red hibiscus flowers with tropical green leaves, vintage botanical illustration, on black background, exotic, tileable, no text" },
  { id: "006", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Watercolor Daisies", prompt: "Seamless pattern of simple white daisies with yellow centers, loose watercolor style, on pale blue background, cheerful and fresh, tileable, no text" },
  { id: "007", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Art Nouveau Lily", prompt: "Seamless pattern of stylized calla lilies with flowing art nouveau lines, gold accents on navy blue background, elegant and refined, tileable, no text" },
  { id: "008", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Forget Me Not", prompt: "Seamless pattern of tiny blue forget-me-not flowers scattered evenly, vintage botanical illustration, on warm cream background, delicate and nostalgic, tileable, no text" },
  { id: "009", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Botanical Garden", prompt: "Seamless pattern of detailed botanical illustrations of mixed flowers and herbs, vintage encyclopedia style, on beige parchment background, scholarly, tileable, no text" },
  { id: "010", theme: "floral", source: "original", sourceRef: "—", sourceUrl: "", name: "Japanese Iris", prompt: "Seamless pattern of Japanese irises in flowing blue ink, sumi-e brush style, on rice paper texture background, zen minimalism, tileable, no text" },

  // 2. MARBLE (011-020)
  { id: "011", theme: "marble", source: "burga", sourceRef: "Vanilla Sand", sourceUrl: "https://burga.com/products/marble-airpods-3-case", name: "Vanilla Sand", prompt: "Seamless pattern of creamy white marble with subtle beige and gray veining, realistic luxury stone texture, elegant and timeless, tileable, no text" },
  { id: "012", theme: "marble", source: "burga", sourceRef: "Golden Coral", sourceUrl: "", name: "Golden Coral", prompt: "Seamless pattern of soft pink marble with golden metallic veins, realistic luxury stone texture, romantic and glamorous, tileable, no text" },
  { id: "013", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Black Onyx", prompt: "Seamless pattern of jet black marble with fine silver and white veining, realistic luxury stone texture, sophisticated and dramatic, tileable, no text" },
  { id: "014", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Rose Quartz", prompt: "Seamless pattern of translucent rose quartz crystal with soft pink tones and white streaks, realistic stone texture, tileable, no text" },
  { id: "015", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Malachite", prompt: "Seamless pattern of deep green malachite with concentric dark and light rings, realistic luxury stone texture, tileable, no text" },
  { id: "016", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Navy Royale", prompt: "Seamless pattern of deep navy blue marble with ornate gold veining, realistic luxury stone texture, regal and opulent, tileable, no text" },
  { id: "017", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Carrara Classic", prompt: "Seamless pattern of pure white Carrara marble with thin gray veins, realistic luxury stone texture, timeless and refined, tileable, no text" },
  { id: "018", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Terracotta", prompt: "Seamless pattern of warm terracotta marble with cream colored veins, realistic earthy stone texture, warm and organic, tileable, no text" },
  { id: "019", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Emerald Jade", prompt: "Seamless pattern of emerald green jade with white and gold streaks, realistic luxury stone texture, tileable, no text" },
  { id: "020", theme: "marble", source: "original", sourceRef: "—", sourceUrl: "", name: "Iridescent Pearl", prompt: "Seamless pattern of iridescent pearlescent marble with rainbow shimmer, realistic luxury stone texture, mystical, tileable, no text" },

  // 3. ANIMAL (021-030)
  { id: "021", theme: "animal", source: "burga", sourceRef: "Celestial", sourceUrl: "", name: "Celestial Cow", prompt: "Seamless pattern of brown and cream cow print, organic irregular shapes, realistic hide texture, rustic chic, tileable, no text" },
  { id: "022", theme: "animal", source: "burga", sourceRef: "Derby Race", sourceUrl: "", name: "Derby Horse", prompt: "Seamless pattern of horses in various poses galloping trotting and standing, hand-drawn navy blue ink sketch, vintage engraving style on cream background, tileable, no text" },
  { id: "023", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Leopard Classic", prompt: "Seamless pattern of classic leopard print spots in black and brown on tan background, realistic fur texture, bold and fashionable, tileable, no text" },
  { id: "024", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Zebra Stripes", prompt: "Seamless pattern of organic zebra stripes in black on white background, realistic and elegant, tileable, no text" },
  { id: "025", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Python Skin", prompt: "Seamless pattern of python snake skin in natural beige and brown tones, detailed scales texture, exotic, tileable, no text" },
  { id: "026", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Giraffe Mosaic", prompt: "Seamless pattern of giraffe print spots in warm brown on golden tan background, organic irregular shapes, tileable, no text" },
  { id: "027", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Tiger Stripes", prompt: "Seamless pattern of tiger stripes in orange and black, bold and fierce, realistic fur texture, tileable, no text" },
  { id: "028", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Pink Leopard", prompt: "Seamless pattern of leopard print spots in black and hot pink on soft pink background, playful and bold, tileable, no text" },
  { id: "029", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Dalmatian Spots", prompt: "Seamless pattern of irregular black spots on white background, minimalist dalmatian print, graphic and clean, tileable, no text" },
  { id: "030", theme: "animal", source: "original", sourceRef: "—", sourceUrl: "", name: "Cheetah Minimal", prompt: "Seamless pattern of small cheetah print spots in black and tan on cream background, refined and subtle, tileable, no text" },

  // 4. FOOD (031-040)
  { id: "031", theme: "food", source: "burga", sourceRef: "Harvest", sourceUrl: "https://burga.com/products/harvest-airpods-pro-3-case", name: "Harvest Tomato", prompt: "Seamless pattern of red tomatoes scattered over red and white gingham checks, graphic food illustration, homey and nostalgic, tileable, no text" },
  { id: "032", theme: "food", source: "burga", sourceRef: "Freshly Picked", sourceUrl: "https://burga.com/products/freshly-picked-airpods-pro-3-case", name: "Freshly Picked", prompt: "Seamless pattern of scattered red strawberries with green leaves, playful hand-drawn style, on cream background, summery and abundant, tileable, no text" },
  { id: "033", theme: "food", source: "burga", sourceRef: "Pickled", sourceUrl: "https://burga.com/products/pickled-airpods-pro-3-case", name: "Pickled", prompt: "Seamless pattern of pickle jars and cucumbers with dill, vintage illustration, on olive green background, quirky vintage charm, tileable, no text" },
  { id: "034", theme: "food", source: "burga", sourceRef: "Honeycomb", sourceUrl: "https://burga.com/products/honeycomb-airpods-pro-3-case", name: "Honeycomb Bee", prompt: "Seamless pattern of honey bees with honeycomb hexagons and yellow gingham accents, graphic illustration, warm and golden, tileable, no text" },
  { id: "035", theme: "food", source: "burga", sourceRef: "Cinnamon Roll", sourceUrl: "https://burga.com/products/cinnamon-roll-airpods-pro-3-case", name: "Cinnamon Roll", prompt: "Seamless pattern of swirled cinnamon rolls with icing, cozy illustration style, on warm beige background, comforting, tileable, no text" },
  { id: "036", theme: "food", source: "burga", sourceRef: "Cherrybomb", sourceUrl: "", name: "Cherry", prompt: "Seamless pattern of red cherries with green stems on black background, glossy and elegant, tileable, no text" },
  { id: "037", theme: "food", source: "original", sourceRef: "—", sourceUrl: "", name: "Lemon Zest", prompt: "Seamless pattern of bright yellow lemons with green leaves, watercolor illustration, on soft blue background, Mediterranean summer, tileable, no text" },
  { id: "038", theme: "food", source: "original", sourceRef: "—", sourceUrl: "", name: "Mushroom Forest", prompt: "Seamless pattern of various woodland mushrooms including red cap and chanterelle, vintage botanical illustration, on dark green background, foraged and whimsical, tileable, no text" },
  { id: "039", theme: "food", source: "original", sourceRef: "—", sourceUrl: "", name: "Coffee Beans", prompt: "Seamless pattern of roasted coffee beans scattered, realistic illustration, on dark brown background, rich and warm, tileable, no text" },
  { id: "040", theme: "food", source: "original", sourceRef: "—", sourceUrl: "", name: "Orange Grove", prompt: "Seamless pattern of bright oranges with green leaves and white blossoms, vintage botanical illustration, on terracotta background, Mediterranean, tileable, no text" },

  // 5. BOTANICAL (041-050)
  { id: "041", theme: "botanical", source: "burga", sourceRef: "Velvet Night", sourceUrl: "", name: "Velvet Ginkgo", prompt: "Seamless pattern of ginkgo leaves in deep navy and gold, art nouveau style, on midnight blue background, elegant and nocturnal, tileable, no text" },
  { id: "042", theme: "botanical", source: "burga", sourceRef: "Barely Yours", sourceUrl: "", name: "Barely Ginkgo", prompt: "Seamless pattern of ginkgo leaves in soft taupe and cream, minimalist botanical, on pale beige background, serene and understated, tileable, no text" },
  { id: "043", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Monstera Jungle", prompt: "Seamless pattern of large monstera leaves in rich green with natural splits, realistic botanical illustration, on dark green background, tropical, tileable, no text" },
  { id: "044", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Fern Lace", prompt: "Seamless pattern of delicate fern fronds in forest green, detailed botanical illustration, on cream background, woodland elegance, tileable, no text" },
  { id: "045", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Palm Shadow", prompt: "Seamless pattern of palm fronds in dark green silhouette style, on warm sand background, minimalist tropical, tileable, no text" },
  { id: "046", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Eucalyptus", prompt: "Seamless pattern of eucalyptus branches with silver-green leaves, watercolor style, on soft white background, fresh and calming, tileable, no text" },
  { id: "047", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Ivy Trellis", prompt: "Seamless pattern of climbing ivy vines with small dark green leaves, vintage botanical illustration, on cream background, English garden, tileable, no text" },
  { id: "048", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Jungle Canopy", prompt: "Seamless pattern of mixed tropical leaves including banana monstera and philodendron, lush and dense, realistic colors, tileable, no text" },
  { id: "049", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Bamboo Grove", prompt: "Seamless pattern of bamboo stalks with slender leaves, minimalist Japanese ink style, on warm white background, zen, tileable, no text" },
  { id: "050", theme: "botanical", source: "original", sourceRef: "—", sourceUrl: "", name: "Pressed Florals", prompt: "Seamless pattern of dried and pressed wildflowers in muted tones, herbarium style, on aged cream background, nostalgic and scholarly, tileable, no text" },

  // 6. GEOMETRIC (051-060)
  { id: "051", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Black White Checker", prompt: "Seamless pattern of bold black and white checkerboard squares, crisp and graphic, minimalist, tileable, no text" },
  { id: "052", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Red Gingham", prompt: "Seamless pattern of classic red and white gingham checks, fresh and country, tileable, no text" },
  { id: "053", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Art Deco Gold", prompt: "Seamless pattern of art deco fan motifs in gold on deep navy background, 1920s luxury style, tileable, no text" },
  { id: "054", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Houndstooth", prompt: "Seamless pattern of classic black and white houndstooth, sophisticated menswear style, tileable, no text" },
  { id: "055", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Argyle", prompt: "Seamless pattern of argyle diamonds in burgundy forest green and cream, preppy classic, tileable, no text" },
  { id: "056", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Retro Circles", prompt: "Seamless pattern of overlapping circles in mustard yellow teal and rust, 1970s retro style, on cream background, tileable, no text" },
  { id: "057", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Minimal Stripes", prompt: "Seamless pattern of clean vertical stripes in navy and cream, minimalist and timeless, tileable, no text" },
  { id: "058", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Triangle Mountains", prompt: "Seamless pattern of stacked triangles forming abstract mountain ranges, geometric, earth tones, tileable, no text" },
  { id: "059", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Hexagon Gold", prompt: "Seamless pattern of connected hexagons in metallic gold and cream, geometric luxury, tileable, no text" },
  { id: "060", theme: "geometric", source: "original", sourceRef: "—", sourceUrl: "", name: "Moroccan Tile", prompt: "Seamless pattern of intricate Moroccan tile motifs in deep blue and white, ornate geometric, tileable, no text" },

  // 7. ABSTRACT (061-070)
  { id: "061", theme: "abstract", source: "burga", sourceRef: "Core", sourceUrl: "", name: "Core Blocks", prompt: "Seamless pattern of abstract color blocks in warm brown sky blue and cream, organic shapes overlapping, midcentury modern, tileable, no text" },
  { id: "062", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Sunset Gradient", prompt: "Seamless smooth gradient blending from coral pink to warm orange to deep purple, sunset colors, painterly wash, tileable, no text" },
  { id: "063", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Ocean Gradient", prompt: "Seamless smooth gradient blending from deep teal to turquoise to pale aqua, ocean colors, painterly, tileable, no text" },
  { id: "064", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Paint Splash", prompt: "Seamless pattern of abstract paint splashes in vibrant red cobalt blue and yellow, expressive and energetic, on white background, tileable, no text" },
  { id: "065", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Organic Blobs", prompt: "Seamless pattern of smooth organic blob shapes in pastel mauve sage and cream, gentle and flowy, tileable, no text" },
  { id: "066", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Brush Strokes", prompt: "Seamless pattern of thick expressive brush strokes in black on white background, sumi-e influence, bold and abstract, tileable, no text" },
  { id: "067", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Watercolor Wash", prompt: "Seamless pattern of soft watercolor washes in dusty rose lavender and butter yellow, painterly and dreamy, tileable, no text" },
  { id: "068", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Risograph Grain", prompt: "Seamless abstract pattern with risograph-style grainy textures in coral pink and teal, overlapping circles, tileable, no text" },
  { id: "069", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Memphis Style", prompt: "Seamless pattern of Memphis design elements - squiggles dots triangles and asterisks, in primary colors on white background, 1980s playful, tileable, no text" },
  { id: "070", theme: "abstract", source: "original", sourceRef: "—", sourceUrl: "", name: "Drip Paint", prompt: "Seamless pattern of vertical paint drips in rich oxblood red on cream background, painterly and raw, tileable, no text" },

  // 8. VINTAGE (071-080)
  { id: "071", theme: "vintage", source: "burga", sourceRef: "La Muse", sourceUrl: "", name: "La Muse Deco", prompt: "Seamless pattern of art deco female silhouettes with fans and geometric frames, gold on black background, 1920s luxury glamour, tileable, no text" },
  { id: "072", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Victorian Damask", prompt: "Seamless pattern of ornate Victorian damask scrollwork in cream on burgundy background, regal and intricate, tileable, no text" },
  { id: "073", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "William Morris", prompt: "Seamless pattern in William Morris style with stylized flowers and vines in muted forest green and rust red, arts and crafts movement, tileable, no text" },
  { id: "074", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Retro 70s Bloom", prompt: "Seamless pattern of stylized 1970s flowers with wavy petals in mustard avocado and burnt orange, groovy and retro, tileable, no text" },
  { id: "075", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Vintage Lace", prompt: "Seamless pattern of delicate white lace doily motifs on soft cream background, romantic and nostalgic, tileable, no text" },
  { id: "076", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Toile de Jouy", prompt: "Seamless pattern in classic toile de jouy style with pastoral scenes in blue on cream background, French country elegance, tileable, no text" },
  { id: "077", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Baroque Gold", prompt: "Seamless pattern of baroque ornamental scrollwork in metallic gold on deep black background, opulent and dramatic, tileable, no text" },
  { id: "078", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Rococo Rose", prompt: "Seamless pattern of rococo garlands with pink roses and gold ribbons on cream background, feminine and ornate, tileable, no text" },
  { id: "079", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Moroccan Medallion", prompt: "Seamless pattern of Moroccan medallions in deep teal and gold on warm terracotta background, mystical vintage, tileable, no text" },
  { id: "080", theme: "vintage", source: "original", sourceRef: "—", sourceUrl: "", name: "Persian Carpet", prompt: "Seamless pattern inspired by Persian carpets with intricate floral medallions in deep red navy and gold, traditional and luxurious, tileable, no text" },

  // 9. CELESTIAL (081-090)
  { id: "081", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Starry Night", prompt: "Seamless pattern of swirling starry night sky inspired by Van Gogh, blue yellow and white, painterly and dreamy, tileable, no text" },
  { id: "082", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Moon Phases", prompt: "Seamless pattern of moon phases from new to full, white on deep navy background, celestial and meditative, tileable, no text" },
  { id: "083", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Constellations", prompt: "Seamless pattern of constellation diagrams with connecting lines and star points, gold on midnight blue background, astronomical, tileable, no text" },
  { id: "084", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Galaxy Nebula", prompt: "Seamless pattern of swirling galaxy nebula with purple pink and blue clouds with white stars, cosmic and dreamy, tileable, no text" },
  { id: "085", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Solar System", prompt: "Seamless pattern of minimalist solar system with planets and orbital rings, line art style, gold on black background, tileable, no text" },
  { id: "086", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Crescent Stars", prompt: "Seamless pattern of crescent moons surrounded by small stars, gold on deep navy background, mystical, tileable, no text" },
  { id: "087", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Sun & Moon", prompt: "Seamless pattern of stylized sun and moon faces with rays and dots, vintage celestial illustration, gold on black background, tileable, no text" },
  { id: "088", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Zodiac Glyphs", prompt: "Seamless pattern of zodiac astrology symbols and constellations, gold on deep purple background, mystical and spiritual, tileable, no text" },
  { id: "089", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Cosmic Ombre", prompt: "Seamless pattern of deep space cosmic ombre blending black navy and indigo with scattered tiny stars, dreamy, tileable, no text" },
  { id: "090", theme: "celestial", source: "original", sourceRef: "—", sourceUrl: "", name: "Gold Stars", prompt: "Seamless pattern of small five-pointed gold stars scattered evenly on deep black background, minimalist celestial, tileable, no text" },

  // 10. COASTAL (091-100)
  { id: "091", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Hokusai Wave", prompt: "Seamless pattern of stylized ocean waves inspired by Hokusai, deep blue with white foam, Japanese woodblock style, tileable, no text" },
  { id: "092", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Palm Sunset", prompt: "Seamless pattern of palm tree silhouettes against coral pink sunset sky, tropical dreamy, tileable, no text" },
  { id: "093", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Tropical Fish", prompt: "Seamless pattern of colorful tropical fish and coral, vintage illustration style, on teal background, underwater tropical, tileable, no text" },
  { id: "094", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Seashells", prompt: "Seamless pattern of various seashells including conch and scallop, watercolor illustration, on soft cream background, beach nostalgia, tileable, no text" },
  { id: "095", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Mediterranean Tile", prompt: "Seamless pattern of blue and white Mediterranean tiles with floral motifs, Greek island style, tileable, no text" },
  { id: "096", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Coral Reef", prompt: "Seamless pattern of coral branches in coral pink and mustard yellow, vintage botanical illustration, on teal background, tileable, no text" },
  { id: "097", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Wave Gradient", prompt: "Seamless pattern of smooth wavy lines in ocean blues and aqua greens, gradient wave, tileable, no text" },
  { id: "098", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Beach Sunset", prompt: "Seamless pattern of abstract beach sunset horizons in coral peach and lavender stripes, dreamy gradient, tileable, no text" },
  { id: "099", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Pineapple", prompt: "Seamless pattern of golden pineapples with green crown leaves, graphic illustration, on pink background, tropical, tileable, no text" },
  { id: "100", theme: "coastal", source: "original", sourceRef: "—", sourceUrl: "", name: "Flamingo Tropical", prompt: "Seamless pattern of pink flamingos with tropical palm leaves, vintage illustration, on teal green background, resort style, tileable, no text" },

  // 11. JAPANESE — Café Haru (101-110) — BURGA 参照
  { id: "101", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Classic", prompt: "Seamless pattern of Japanese wagashi sweets mochi dango and matcha desserts with tiny sakura petals, pastel illustration on deep burgundy background, nostalgic café mood, tileable, no text" },
  { id: "102", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Matcha", prompt: "Seamless pattern of matcha bowls whisks and green tea sweets with scattered sakura petals, soft painterly style on sage matcha green background, calm and refined, tileable, no text" },
  { id: "103", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Sakura", prompt: "Seamless pattern of dango skewers and pink mochi with cherry blossom petals floating, kawaii pastel style on blush pink background, springtime sweetness, tileable, no text" },
  { id: "104", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Cream", prompt: "Seamless pattern of delicate daifuku and senbei scattered with sakura, minimalist Japanese illustration on warm cream background, understated elegance, tileable, no text" },
  { id: "105", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Noir", prompt: "Seamless pattern of wagashi sweets and teacups in metallic gold on deep black background, luxurious Japanese café aesthetic, tileable, no text" },
  { id: "106", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Ivory", prompt: "Seamless pattern of soft blush pink mochi and petit fours, minimal Japanese café style on ivory background, serene and feminine, tileable, no text" },
  { id: "107", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Indigo", prompt: "Seamless pattern of white mochi daifuku and sakura branches on deep indigo blue background, traditional Japanese elegance, tileable, no text" },
  { id: "108", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Sunset", prompt: "Seamless pattern of taiyaki dorayaki and dango sweets on warm peach sunset background, cozy dessert café mood, tileable, no text" },
  { id: "109", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Tea Time", prompt: "Seamless pattern of Japanese teapots yunomi cups and small dango skewers on muted olive background, tea ceremony serenity, tileable, no text" },
  { id: "110", theme: "japanese", source: "burga", sourceRef: "Café Haru", sourceUrl: "https://burga.jp/products/cafe-haru-airpods-pro-3-case", name: "Café Haru Neo", prompt: "Seamless pattern of stylized wagashi and sakura in modern graphic style on soft lavender background, contemporary Japanese café, tileable, no text" },

  // 12. JAPANESE — Maneki Neko (111-120) — BURGA 参照
  { id: "111", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Classic", prompt: "Seamless pattern of white maneki neko lucky cats raising paws with pink cherry blossoms, traditional Japanese illustration on deep burgundy background, auspicious and charming, tileable, no text" },
  { id: "112", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Noir", prompt: "Seamless pattern of metallic gold maneki neko cats with cherry blossom branches on jet black background, luxurious Japanese talisman, tileable, no text" },
  { id: "113", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Pastel", prompt: "Seamless pattern of white lucky cats and tiny sakura on soft pastel pink background, kawaii Japanese charm, tileable, no text" },
  { id: "114", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Indigo", prompt: "Seamless pattern of calico maneki neko with sakura petals on deep indigo blue background, traditional ukiyo-e mood, tileable, no text" },
  { id: "115", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Cream", prompt: "Seamless pattern of red-collared maneki neko and plum blossoms on warm cream background, vintage Japanese folk style, tileable, no text" },
  { id: "116", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Gold", prompt: "Seamless pattern of gold foil lucky cats with ornate sakura motifs on rich vermillion red background, opulent Japanese luxury, tileable, no text" },
  { id: "117", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Mint", prompt: "Seamless pattern of peach-toned maneki neko and sakura on soft mint green background, fresh and playful Japanese charm, tileable, no text" },
  { id: "118", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Moonlit", prompt: "Seamless pattern of white maneki neko with crescent moons and sakura on deep navy night background, mystical Japanese folk art, tileable, no text" },
  { id: "119", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Watercolor", prompt: "Seamless pattern of softly painted watercolor maneki neko and sakura branches on warm ivory background, gentle Japanese watercolor, tileable, no text" },
  { id: "120", theme: "japanese", source: "burga", sourceRef: "Maneki Neko", sourceUrl: "https://burga.jp/products/maneki-neko-airpods-pro-3-case", name: "Maneki Neko Lineart", prompt: "Seamless pattern of minimalist line-art maneki neko cats and sakura outlines on clean white background, modern Japanese minimal, tileable, no text" },

  // 13. JAPANESE — Yume (121-130) — BURGA 参照
  { id: "121", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Classic", prompt: "Seamless pattern of playing card suits hearts spades diamonds clubs and small pink koi fish on deep burgundy background, dreamy Japanese maximalist mood, tileable, no text" },
  { id: "122", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Black", prompt: "Seamless pattern of red and white playing card suits with koi fish on jet black background, bold and dramatic, tileable, no text" },
  { id: "123", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Cream", prompt: "Seamless pattern of navy blue playing card suits and small fish scattered on warm cream background, vintage whimsical, tileable, no text" },
  { id: "124", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Pastel", prompt: "Seamless pattern of pastel multicolored playing card suits and tiny koi on white background, playful and soft, tileable, no text" },
  { id: "125", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Gold", prompt: "Seamless pattern of metallic gold playing card suits and koi fish silhouettes on deep navy background, opulent art deco Japanese, tileable, no text" },
  { id: "126", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Neon", prompt: "Seamless pattern of neon bright playing card suits and electric koi on jet black background, retro arcade energy, tileable, no text" },
  { id: "127", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Koi", prompt: "Seamless pattern of orange and pink koi fish swimming with small playing card suits on deep burgundy background, ukiyo-e fish focus, tileable, no text" },
  { id: "128", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Vintage", prompt: "Seamless pattern of antique playing card suits in burgundy and cream with aged koi illustrations, vintage tarot deck aesthetic, tileable, no text" },
  { id: "129", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Ukiyo", prompt: "Seamless pattern of ukiyo-e style koi fish with stylized playing card suits on traditional Japanese woodblock background, tileable, no text" },
  { id: "130", theme: "japanese", source: "burga", sourceRef: "Yume", sourceUrl: "https://burga.jp/products/yume-airpods-pro-3-case", name: "Yume Deco", prompt: "Seamless pattern of art deco geometric playing card suits with stylized fish in black and gold, 1920s luxury, tileable, no text" },

  // 14. ABSTRACT — Distorsion (131-140) — BURGA 参照
  { id: "131", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Classic", prompt: "Seamless pattern of shattered glass cracks with flowing fluid lines in cobalt blue tones on deep navy background, abstract modern distortion, tileable, no text" },
  { id: "132", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Noir", prompt: "Seamless pattern of white crack lines and flowing abstract shapes on jet black background, dramatic shattered glass effect, tileable, no text" },
  { id: "133", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Sunset", prompt: "Seamless pattern of orange and red crack lines flowing across coral sunset background, warm abstract distortion, tileable, no text" },
  { id: "134", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Gold", prompt: "Seamless pattern of metallic gold shattered glass cracks on deep black background, luxurious broken surface, tileable, no text" },
  { id: "135", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Ink", prompt: "Seamless pattern of indigo ink-like cracks flowing across textured rice paper background, sumi-e abstract, tileable, no text" },
  { id: "136", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Emerald", prompt: "Seamless pattern of emerald green cracks and flowing distortion on dark teal background, mysterious abstract, tileable, no text" },
  { id: "137", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Glitch", prompt: "Seamless pattern of hot pink digital glitch cracks on charcoal gray background, cyberpunk distortion, tileable, no text" },
  { id: "138", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Mono", prompt: "Seamless pattern of grayscale crack lines and flowing abstract distortion, high contrast minimal, tileable, no text" },
  { id: "139", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Cyber", prompt: "Seamless pattern of teal digital crack lines with flowing circuit-like distortion on midnight blue background, futuristic cyber, tileable, no text" },
  { id: "140", theme: "abstract", source: "burga", sourceRef: "Distorsion", sourceUrl: "https://burga.jp/products/distorsion-airpods-pro-3-case", name: "Distorsion Lava", prompt: "Seamless pattern of orange lava flow cracks spreading across deep crimson red background, molten abstract, tileable, no text" },

  // 15. ABSTRACT — Out of Line (141-150) — BURGA 参照
  { id: "141", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Classic", prompt: "Seamless pattern of flowing blue and white wave lines, smooth curving abstract stripes, minimalist modern, tileable, no text" },
  { id: "142", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Noir", prompt: "Seamless pattern of flowing black wave lines on clean white background, graphic minimal stripes, tileable, no text" },
  { id: "143", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Rainbow", prompt: "Seamless pattern of flowing pastel rainbow wave lines, soft curving abstract stripes, dreamy, tileable, no text" },
  { id: "144", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Sunset", prompt: "Seamless pattern of flowing coral peach and orange wave lines on warm cream background, sunset gradient abstract, tileable, no text" },
  { id: "145", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Emerald", prompt: "Seamless pattern of flowing emerald green wave lines on dark forest background, organic abstract, tileable, no text" },
  { id: "146", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Gold", prompt: "Seamless pattern of thin metallic gold wave lines on jet black background, elegant abstract stripes, tileable, no text" },
  { id: "147", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Navy", prompt: "Seamless pattern of white curving wave lines on deep navy background, clean nautical abstract, tileable, no text" },
  { id: "148", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Sand", prompt: "Seamless pattern of flowing sand dune wave lines in ivory and beige, warm organic abstract, tileable, no text" },
  { id: "149", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Cloud", prompt: "Seamless pattern of pale cloud-like flowing wave lines on soft sky blue background, airy abstract, tileable, no text" },
  { id: "150", theme: "abstract", source: "burga", sourceRef: "Out of Line", sourceUrl: "https://burga.jp/products/out-of-line-airpods-pro-3-case", name: "Out of Line Storm", prompt: "Seamless pattern of stormy gray flowing wave lines with dramatic contrast on charcoal background, moody abstract, tileable, no text" },

  // 16. ABSTRACT — Void (151-160) — BURGA 参照
  { id: "151", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Classic", prompt: "Seamless pattern of subtle black crack lines on deep charcoal background, moody monochrome abstract, tileable, no text" },
  { id: "152", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void White", prompt: "Seamless pattern of delicate white crack lines spreading across jet black background, minimalist monochrome, tileable, no text" },
  { id: "153", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Grey", prompt: "Seamless pattern of layered gray abstract cracks with varied thickness on warm stone background, sophisticated monochrome, tileable, no text" },
  { id: "154", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Charcoal", prompt: "Seamless pattern of charcoal gradient cracks fading from dark to light, moody abstract depth, tileable, no text" },
  { id: "155", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Concrete", prompt: "Seamless pattern of cracked concrete texture in muted gray tones, raw industrial abstract, tileable, no text" },
  { id: "156", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Splatter", prompt: "Seamless pattern of monochrome ink splatter and crack lines on bone white background, expressive abstract, tileable, no text" },
  { id: "157", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Glitch", prompt: "Seamless pattern of monochrome glitch distortion and broken lines on black background, digital abstract, tileable, no text" },
  { id: "158", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Holes", prompt: "Seamless pattern of irregular dark holes and cracks scattered on charcoal gray background, mysterious abstract, tileable, no text" },
  { id: "159", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Scribble", prompt: "Seamless pattern of scribbled dark ink abstract lines on off-white background, raw sketchbook feel, tileable, no text" },
  { id: "160", theme: "abstract", source: "burga", sourceRef: "Void", sourceUrl: "https://burga.jp/products/void-airpods-pro-3-case", name: "Void Mesh", prompt: "Seamless pattern of intricate shadow mesh lines in monochrome gray, layered abstract depth, tileable, no text" },

  // 17. OUTDOOR — Basecamp (161-170) — BURGA 参照
  { id: "161", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Classic", prompt: "Seamless pattern of vintage outdoor adventure patches with mountains pine trees and badges in earth tones on kraft paper background, retro scouting, tileable, no text" },
  { id: "162", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Retro", prompt: "Seamless pattern of retro 70s camping badges with sunsets tents and hiking trails, warm rust and mustard palette, tileable, no text" },
  { id: "163", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Summit", prompt: "Seamless pattern of hand-drawn mountain line art and peak sketches on warm kraft background, minimalist adventure, tileable, no text" },
  { id: "164", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Pine", prompt: "Seamless pattern of pine tree silhouettes and scout patch badges in forest green and cream, woodland adventure, tileable, no text" },
  { id: "165", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Compass", prompt: "Seamless pattern of vintage compasses topographic maps and trail markers in navy and tan, explorer journal aesthetic, tileable, no text" },
  { id: "166", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Ski", prompt: "Seamless pattern of vintage ski resort badges with snowy peaks and chairlifts in cream and red, retro alpine, tileable, no text" },
  { id: "167", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Parks", prompt: "Seamless pattern of national park style badges with wildlife and mountain emblems in earth tones, americana wilderness, tileable, no text" },
  { id: "168", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Wildlife", prompt: "Seamless pattern of vintage wildlife patches with bears wolves and deer silhouettes on forest green background, rugged nature, tileable, no text" },
  { id: "169", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Lake", prompt: "Seamless pattern of canoe lake and pine badges in blue and sage green, tranquil wilderness, tileable, no text" },
  { id: "170", theme: "outdoor", source: "burga", sourceRef: "Basecamp", sourceUrl: "https://burga.jp/products/basecamp-airpods-pro-3-case", name: "Basecamp Firelight", prompt: "Seamless pattern of campfires starry skies and tent badges on deep navy background, nocturnal camping mood, tileable, no text" },

  // 18. GEOMETRIC — On Read (171-180) — BURGA 参照
  { id: "171", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Classic", prompt: "Seamless pattern of bold red vertical geometric blocks and stripes on cream background, graphic modern minimalism, tileable, no text" },
  { id: "172", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Bauhaus", prompt: "Seamless pattern of primary color geometric blocks squares and rectangles in bauhaus style on off-white background, tileable, no text" },
  { id: "173", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Mono", prompt: "Seamless pattern of black and red vertical blocks arranged in grid, high contrast graphic design, tileable, no text" },
  { id: "174", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Pastel", prompt: "Seamless pattern of pastel rainbow geometric blocks in soft blush sage and butter yellow, modern minimalist, tileable, no text" },
  { id: "175", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Chevron", prompt: "Seamless pattern of minimal chevron stripes in deep red and cream, sharp geometric modern, tileable, no text" },
  { id: "176", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Modern", prompt: "Seamless pattern of modernist color blocks in warm terracotta forest green and cream, midcentury design, tileable, no text" },
  { id: "177", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Earth", prompt: "Seamless pattern of earth tone geometric grid with rust ochre and olive rectangles, organic modernism, tileable, no text" },
  { id: "178", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Flag", prompt: "Seamless pattern of flag-style horizontal stripes in bold red navy and cream, nautical graphic, tileable, no text" },
  { id: "179", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Primary", prompt: "Seamless pattern of primary color blocks red yellow and blue arranged mondrian style, constructivist art, tileable, no text" },
  { id: "180", theme: "geometric", source: "burga", sourceRef: "On Read", sourceUrl: "https://burga.jp/products/on-read-airpods-pro-3-case", name: "On Read Checker", prompt: "Seamless pattern of bauhaus style checkerboard with red and cream squares of varying sizes, playful modernist, tileable, no text" },

  // 19. GEOMETRIC — Orbit (181-190) — BURGA 参照
  { id: "181", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Classic", prompt: "Seamless pattern of minimal black dots scattered with subtle soft blur effect on clean white background, modern geometric, tileable, no text" },
  { id: "182", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Polka", prompt: "Seamless pattern of large black polka dots evenly spaced on cream background, classic graphic design, tileable, no text" },
  { id: "183", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Halftone", prompt: "Seamless pattern of halftone gradient black dots transitioning from dense to sparse on white background, print design, tileable, no text" },
  { id: "184", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Cream", prompt: "Seamless pattern of scattered dark navy dots on warm cream background, minimalist elegant, tileable, no text" },
  { id: "185", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Moire", prompt: "Seamless pattern of overlapping dot grids creating moire interference effect in black and white, optical geometric, tileable, no text" },
  { id: "186", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Gradient", prompt: "Seamless pattern of gradient concentric dot circles fading from bold center to soft edge, spatial geometric, tileable, no text" },
  { id: "187", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Neon", prompt: "Seamless pattern of neon pink and cyan dots with soft glow blur on jet black background, retro futurism, tileable, no text" },
  { id: "188", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Fade", prompt: "Seamless pattern of black dots gradually morphing into lines with soft blur, transition geometric abstract, tileable, no text" },
  { id: "189", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Atomic", prompt: "Seamless pattern of atomic cluster diagram with dots and connecting lines on pale blue background, scientific minimal, tileable, no text" },
  { id: "190", theme: "geometric", source: "burga", sourceRef: "Orbit", sourceUrl: "https://burga.jp/products/orbit-airpods-pro-3-case", name: "Orbit Stellar", prompt: "Seamless pattern of tiny white dots scattered like a dense star field on deep black background, cosmic minimal, tileable, no text" },

  // 20. ABSTRACT — Aftershock (191-200) — BURGA 参照
  { id: "191", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Classic", prompt: "Seamless pattern of swirling monochrome lines creating optical illusion with wave motion, black on white abstract, tileable, no text" },
  { id: "192", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Hypnotic", prompt: "Seamless pattern of hypnotic concentric rings in black and white creating visual vibration, op art mesmerizing, tileable, no text" },
  { id: "193", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Spiral", prompt: "Seamless pattern of op art spiral tunnel with black and white swirling lines, dizzying geometric illusion, tileable, no text" },
  { id: "194", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Psychedelic", prompt: "Seamless pattern of psychedelic swirling waves in black and white, 1960s groovy optical art, tileable, no text" },
  { id: "195", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Rings", prompt: "Seamless pattern of concentric undulating rings in crisp black and white, bridget riley inspired op art, tileable, no text" },
  { id: "196", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Squares", prompt: "Seamless pattern of op art warped squares with distorted perspective in black and white, visual vibration, tileable, no text" },
  { id: "197", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Vibrate", prompt: "Seamless pattern of tightly packed parallel wavy lines in black and white creating vibration effect, op art tension, tileable, no text" },
  { id: "198", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Moire", prompt: "Seamless pattern of overlapping wavy lines creating moire interference in stark black and white, hypnotic abstract, tileable, no text" },
  { id: "199", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Fractal", prompt: "Seamless pattern of fractal spiral curls repeating at different scales in monochrome, mathematical beauty, tileable, no text" },
  { id: "200", theme: "abstract", source: "burga", sourceRef: "Aftershock", sourceUrl: "https://burga.jp/products/aftershock-airpods-pro-3-case", name: "Aftershock Ribbon", prompt: "Seamless pattern of twisted monochrome ribbon waves flowing across the canvas, elegant op art motion, tileable, no text" },
];
